### ISSUE TITLE
can't run app due to 'NoSucnMethodError'

### ISSUE THREAD

**Issue by guxun12** [iampawan/Flutter-Music-Player#13]
**see the screenshort**
![4071532503867_ pic](https://user-images.githubusercontent.com/7553670/43186001-0f5e4fa8-9020-11e8-96a2-7763ed445c94.jpg)
logcat:
`07-25 15:35:16.207 24781-24803/com.example.flutterhelloworld I/flutter: When the exception was thrown, this was the stack:
07-25 15:35:16.220 24781-24803/com.example.flutterhelloworld I/flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
    #1      MPListView.build (package:flutter_hello_world/widgets/mp_lisview.dart:15:33)
07-25 15:35:16.221 24781-24803/com.example.flutterhelloworld I/flutter: #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3695:28)
    #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
    #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
    #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
    #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
    #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
    #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
    #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
    #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
    #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
    #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
    #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
    #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
    #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
    #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
    #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
    #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
    #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
    #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)`

**Comment by femibiwoye** [comment]
Sorted it out. It has to do with permission.

Goto your mobile settings -> Apps & Notification -> Select the app -> Permission -> Enable disabled permission.
